#!/usr/bin/env bash
sudo ./pagerank-process.sh ALBERTA_alberta_education_curriculum
sudo ./pagerank-process.sh ALBERTA_alberta_floods_2013
sudo ./pagerank-process.sh ALBERTA_alberta_oil_sands
sudo ./pagerank-process.sh ALBERTA_canadian_business_grey_literature
sudo ./pagerank-process.sh ALBERTA_edmonton_public_library
sudo ./pagerank-process.sh ALBERTA_energy_environment
sudo ./pagerank-process.sh ALBERTA_fort_mcmurray_wildfire_2016
sudo ./pagerank-process.sh ALBERTA_government_information
sudo ./pagerank-process.sh ALBERTA_hcf_alberta_online_encyclopedia
sudo ./pagerank-process.sh ALBERTA_health_sciences_grey_literature
sudo ./pagerank-process.sh ALBERTA_heritage_community_foundation
sudo ./pagerank-process.sh ALBERTA_humanities_computing
sudo ./pagerank-process.sh ALBERTA_lfrancophonie_de_louest_canadien
sudo ./pagerank-process.sh ALBERTA_ottawa_shooting_october_2014
sudo ./pagerank-process.sh ALBERTA_prairie_provinces
sudo ./pagerank-process.sh ALBERTA_web_archive_general
sudo ./pagerank-process.sh ALBERTA_western_canadian_film
sudo ./pagerank-process.sh SFU_bc_local_government
sudo ./pagerank-process.sh SFU_government_of_canada
sudo ./pagerank-process.sh SFU_library_website
sudo ./pagerank-process.sh SFU_ngos
sudo ./pagerank-process.sh SFU_pkp
sudo ./pagerank-process.sh SFU_sfu_affiliated
sudo ./pagerank-process.sh TORONTO_canadian_labour_unions
sudo ./pagerank-process.sh TORONTO_Canadian_Political_Parties
sudo ./pagerank-process.sh TORONTO_federal_election_candidate_sites_2015
sudo ./pagerank-process.sh TORONTO_snowden_archive
sudo ./pagerank-process.sh TORONTO_toronto_2015_pan_am_parapan_american_games
sudo ./pagerank-process.sh TORONTO_tspace
sudo ./pagerank-process.sh UVIC_anarchist_archives
sudo ./pagerank-process.sh UVIC_at_risk_websites
sudo ./pagerank-process.sh UVIC_bc_teachers_labour_dispute_2014
sudo ./pagerank-process.sh UVIC_environmental_organizations_and_resources_of_bc
sudo ./pagerank-process.sh UVIC_maps_at_risk
sudo ./pagerank-process.sh UVIC_trans_web
sudo ./pagerank-process.sh UVIC_University_of_Victoria_50th_Anniversary_1963-2013
sudo ./pagerank-process.sh UVIC_University_of_Victoria_Calendar
sudo ./pagerank-process.sh UVIC_University_of_Victoria_Digital_Scholarship_Websites
sudo ./pagerank-process.sh UVIC_University_of_Victoria_Faculty_Association_Certification_2014
sudo ./pagerank-process.sh UVIC_University_of_Victoria_Research_Centres_Groups_and_Corporate_Entities
sudo ./pagerank-process.sh UVIC_University_of_Victoria_Websites
sudo ./pagerank-process.sh UVIC_Vancouver_Island_Local_Governments
sudo ./pagerank-process.sh UVIC_Vancouver_Island_Local_News
sudo ./pagerank-process.sh WAHR_elxn42
sudo ./pagerank-process.sh WAHR_panamapapers
sudo ./pagerank-process.sh WAHR_ymmfire
sudo ./pagerank-process.sh WINNIPEG_oral_history_centre
sudo ./pagerank-process.sh WINNIPEG_our_digitized_collections
sudo ./pagerank-process.sh WINNIPEG_racism_in_winnipeg
sudo ./pagerank-process.sh WINNIPEG_truth_reconciliation
sudo ./pagerank-process.sh WINNIPEG_uofw_website